### PR TITLE
Support for PYTHONOPTIMIZE=2, fix tests on PYTHONOPTIMIZE=1, 2

### LINKED ISSUE #208: Webtest fails with PYTHONOPTIMIZE=2
It seems that webtest currently doesn't support enabling full python optimization with PYTHONOPTIMIZE=2, is this a known issue?

**To Reproduce**

1. Run tests with enviroment PYTHONOPTIMIZE=2

eg:

```
TOX_TESTENV_PASSENV=PYTHONOPTIMIZE PYTHONOPTIMIZE=2 tox
```

2.  See error

```
tests/test_app.py:5: in <module>
    from webtest.compat import to_bytes
webtest/__init__.py:9: in <module>
    from webtest.app import TestApp
webtest/app.py:89: in <module>
    class TestApp(object):
webtest/app.py:466: in TestApp
    post_json = utils.json_method('POST')
webtest/utils.py:39: in json_method
    wrapper.__doc__ = json_method.__doc__ % subst
E   TypeError: unsupported operand type(s) for %: 'NoneType' and 'dict'
```

This code is trying to update the docstring, which doesn't exist under `PYTHONOPTIMIZE=2`

**Expected behavior**
Tests to pass.

### PR DESCRIPTION
**Pull request by therefromhere**
* skip tests that rely on assert if optimize is enabled
* skip docstring test if PYTHONOPTIMIZE=2
* try/except on docstring handling in case of PYTHONOPTIMIZE=2

Resolves #208 

Please let me know what you think, I'm not sure this is the right approach for fixing the test failures - for one I think `webtest.response.TestResponse.follow` should be raising an exception instead of doing `assert 300 <= self.status_int < 400`.  A non 3xx response would hit a keyerror when trying to do `_follow` if PYTHONOPTIMIZE>=1.

### CODE REVIEW

**Comment by gawel** [comment]
It's weird that you have to skip some tests (except for docstring related stuff). Should'nt we have the same behavior ?

And just because I'm curious, why do you need PYTHONOPTIMIZE ?

**Comment by therefromhere** [comment]
I agree we aim for the same behaviour, but some of the skipped tests were checking for asserts - which won't fire when optimize is enabled.

There are probably some tests that could be hit though - as I mentioned above I think if checks are part of the core functionality of the test code - eg status code check in `follow()` it maybe they shouldn't use assert (explicitly raise AssertionError instead maybe?).

Since you're curious :) , I'm experimenting running my project with PYTHONOPTIMIZE and I wanted to run my tests both with and without PYTHONOPTIMIZE enabled, to keep my test environment similar to my run environment.

**Comment by gawel** [comment]
Replacing assert statements by some AssertionError seems the best option. I guess this wont change the behavior at all

**Comment by gawel** [comment]
Well, if this feets your needs thats ok for me. The amount of skipIf seems acceptable. Thanks

**Pull request merged**
