### PR TITLE
Add `get_json` method to TestApp.

### PR DESCRIPTION
**Pull request by luhn**
Despite being [in the documentation](https://webtest.readthedocs.org/en/latest/testapp.html#making-json-requests), it doesn't actually exist.

### CODE REVIEW

**Comment by batisteo** [comment]
The Django method [`request.is_ajax()`](https://docs.djangoproject.com/en/stable/_modules/django/http/request/#HttpRequest.is_ajax) looks for the header `HTTP_X_REQUESTED_WITH: XMLHttpRequest`

I’d actually like `TestApp.get_json` as a shorthand for 
```python
response = self.app.get(url, headers={
    'X_REQUESTED_WITH': 'XMLHttpRequest'
})
```

**Comment by gawel** [comment]
That's wrong too. An XMLHttpRequest can return any content type (xml, json, html, js) even if json is kind of a standard.

**Comment by batisteo** [comment]
How about `get_ajax()`?

**Comment by batisteo** [comment]
Never mind, I found the what I needed [in the docs](http://webtest.pythonpaste.org/en/latest/api.html#webtest.app.TestApp.get):
```python
response = self.app.get(url, xhr=True)
```

Awesome API :smile:

**Pull request closed without merging**
