### PR TITLE
Add referer header to request made using response.click(), response.clickbutton() and form.submit()

### PR DESCRIPTION
**Pull request by bdauvergne**

### CODE REVIEW

**Comment by mmerickel** [comment]
It seems odd to send a PR to a testing framework that includes no tests. :-) Can you do that and fix the errors above please?

**Comment by bdauvergne** [comment]
Sorry for that. I will fix the bugs.

**Comment by bdauvergne** [comment]
Ok now I'll add tests.

**Comment by bdauvergne** [comment]
Tests added.

**Pull request merged**
